//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ABISEntities : DbContext
    {
        public ABISEntities()
            : base("name=ABISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CITY> CITies { get; set; }
        public virtual DbSet<CLIENT> CLIENTs { get; set; }
        public virtual DbSet<COMPENSATION> COMPENSATIONs { get; set; }
        public virtual DbSet<COMPENSATION_TYPE> COMPENSATION_TYPE { get; set; }
        public virtual DbSet<DIVISION> DIVISIONs { get; set; }
        public virtual DbSet<FAMILY> FAMILies { get; set; }
        public virtual DbSet<FAMILY_TYPE> FAMILY_TYPE { get; set; }
        public virtual DbSet<IRS_TYPE> IRS_TYPE { get; set; }
        public virtual DbSet<LABOR_CATALOG> LABOR_CATALOG { get; set; }
        public virtual DbSet<LABOR_CATEGORY> LABOR_CATEGORY { get; set; }
        public virtual DbSet<MARKET> MARKETs { get; set; }
        public virtual DbSet<MEETING> MEETINGs { get; set; }
        public virtual DbSet<ORGANIZATION> ORGANIZATIONs { get; set; }
        public virtual DbSet<PROJECT> PROJECTs { get; set; }
        public virtual DbSet<PROJECT_CLIENT> PROJECT_CLIENT { get; set; }
        public virtual DbSet<PROJECT_STAFF> PROJECT_STAFF { get; set; }
        public virtual DbSet<STAFF> STAFFs { get; set; }
        public virtual DbSet<STATE> STATEs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<WORKING_MONTH> WORKING_MONTH { get; set; }
    }
}
