//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        public CLIENT()
        {
            this.PROJECT_CLIENT = new HashSet<PROJECT_CLIENT>();
        }
    
        public long ClientID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public decimal WorkPhone { get; set; }
        public Nullable<decimal> MobilePhone { get; set; }
    
        public virtual ICollection<PROJECT_CLIENT> PROJECT_CLIENT { get; set; }
    }
}
