//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIVISION
    {
        public DIVISION()
        {
            this.PROJECT_STAFF = new HashSet<PROJECT_STAFF>();
        }
    
        public int DivisionID { get; set; }
        public decimal DivisionNumber { get; set; }
        public string DivisionName { get; set; }
    
        public virtual ICollection<PROJECT_STAFF> PROJECT_STAFF { get; set; }
    }
}
