//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAMILY_TYPE
    {
        public FAMILY_TYPE()
        {
            this.FAMILies = new HashSet<FAMILY>();
        }
    
        public long FamilyTypeID { get; set; }
        public string FamilyType { get; set; }
    
        public virtual ICollection<FAMILY> FAMILies { get; set; }
    }
}
