//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IRS_TYPE
    {
        public IRS_TYPE()
        {
            this.COMPENSATIONs = new HashSet<COMPENSATION>();
        }
    
        public int IRSTypeID { get; set; }
        public string IRSType { get; set; }
    
        public virtual ICollection<COMPENSATION> COMPENSATIONs { get; set; }
    }
}
