//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEETING
    {
        public long MeetingID { get; set; }
        public long StaffID { get; set; }
        public byte[] Purpose { get; set; }
        public byte[] TalkingPoints { get; set; }
        public byte[] ActionItems { get; set; }
        public byte[] OpenIssues { get; set; }
    
        public virtual STAFF STAFF { get; set; }
    }
}
