//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANIZATION
    {
        public ORGANIZATION()
        {
            this.PROJECTs = new HashSet<PROJECT>();
        }
    
        public long OrganizationID { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationAcronym { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
    
        public virtual ICollection<PROJECT> PROJECTs { get; set; }
    }
}
