//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT
    {
        public PROJECT()
        {
            this.PROJECT_CLIENT = new HashSet<PROJECT_CLIENT>();
            this.PROJECT_STAFF = new HashSet<PROJECT_STAFF>();
        }
    
        public long ProjectID { get; set; }
        public long OrganizationID { get; set; }
        public string ProjectName { get; set; }
        public decimal ProjectNumber { get; set; }
        public System.DateTime ProjectStartDate { get; set; }
        public System.DateTime ProjectEndDate { get; set; }
        public string Description { get; set; }
    
        public virtual ORGANIZATION ORGANIZATION { get; set; }
        public virtual ICollection<PROJECT_CLIENT> PROJECT_CLIENT { get; set; }
        public virtual ICollection<PROJECT_STAFF> PROJECT_STAFF { get; set; }
    }
}
