//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_STAFF
    {
        public PROJECT_STAFF()
        {
            this.WORKING_MONTH = new HashSet<WORKING_MONTH>();
        }
    
        public long ProjectID { get; set; }
        public long StaffID { get; set; }
        public Nullable<int> MarketID { get; set; }
        public int DivisionID { get; set; }
        public bool TaskLeadInd { get; set; }
        public bool AccountManagerInd { get; set; }
        public Nullable<decimal> HourlyPay { get; set; }
        public Nullable<decimal> BillRate { get; set; }
    
        public virtual DIVISION DIVISION { get; set; }
        public virtual MARKET MARKET { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual ICollection<WORKING_MONTH> WORKING_MONTH { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
