//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKING_MONTH
    {
        public long WorkingMonthInd { get; set; }
        public long ProjectID { get; set; }
        public long StaffID { get; set; }
        public decimal Month { get; set; }
        public decimal Year { get; set; }
        public decimal BillablePercentage { get; set; }
        public decimal ApproximateHoursPerWeek { get; set; }
        public decimal FringePercentage { get; set; }
        public decimal OverheadPercentage { get; set; }
        public decimal GAPercentage { get; set; }
    
        public virtual PROJECT_STAFF PROJECT_STAFF { get; set; }
    }
}
